language: cpp

sudo: required
dist: trusty

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y cxxtest libfuse-dev

install: make

script: make test

