language: rust

rust:
    - stable
    - beta
    - nightly

matrix:
    allow_failures:
        - rust: nightly
    fast_finish: true

addons:
    apt:
        update: true
        packages:
            - libfuse-dev
